apiRules:
- exclude:
    uidRegex: ^BCCertMaker
- exclude:
    uidRegex: ^Org\.BouncyCastle\.
- exclude:
    uidRegex: ^SmartAssembly\.
- exclude:
    uidRegex: ^FiddlerCore\.Utilities\.SmartAssembly\.